name: Publish docs to GitHub Pages
on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: gradle

      - name: Publish docs to gh-pages branch
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.name "github-actions-bot"
          git config user.email "support+actions@github.com"
          
          ./gradlew dokkaHtmlPublish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}